# Step 6: Get Changed Files with Diff
- name: Get Changed Files with Diff
  id: changes
  run: |
    git fetch origin main
    if [ $(git rev-list --count HEAD) -eq 1 ]; then
      echo "First commit, taking all files."
      git ls-files > changed_files.txt
      git diff HEAD --color=never > changes.diff
    else
      git diff origin/main HEAD --color=never > changes.diff
      git diff --name-only origin/main HEAD > changed_files.txt
    fi
    echo "Changed files:"
    cat changed_files.txt

# Step 9: Send Email Notification with Diff
- name: Send Email Notification
  run: |
    echo "Sending Email Notification"
    EMAIL_BODY="<html>
    <head>
      <title>Doap.com Repo Deployed</title>
    </head>
    <body>
      <p><strong>Files Changed:</strong></p>
      <ul>"
    while read -r file; do
      EMAIL_BODY+="<li>$file</li>"
    done < changed_files.txt
    EMAIL_BODY+="</ul><p><strong>Git Diff Details:</strong></p><pre>"
    EMAIL_BODY+="$(cat changes.diff | sed 's/&/&amp;/g; s/</&lt;/g; s/>/&gt;/g')" # Escape HTML
    EMAIL_BODY+="</pre>
    <p>Deployed to repo and fleet: <a href='https://github.com/menached/doap.com/actions'>https://github.com/menached/doap.com/actions</a></p>
    </body>
    </html>"
    echo "$EMAIL_BODY" | mail -s "Doap.com Repo Deployed" -a "Content-Type: text/html" info@doap.com

