name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH Agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Install Mailutils
      - name: Install Mailutils
        run: |
          sudo apt update
          sudo apt install -y mailutils

      # Step 4: Copy Files to Apache vhost and Send Email
      - name: Deploy Files and Notify
        run: |
          echo "Ensuring target directories exist on the server..."
          ssh -o StrictHostKeyChecking=no dmenache@deb1.doap.com '[ ! -d /var/www/doap.com/inc ] && mkdir -p /var/www/doap.com/inc'
          ssh -o StrictHostKeyChecking=no dmenache@deb1.doap.com '[ ! -d /var/www/doap.com/images ] && mkdir -p /var/www/doap.com/images'

          echo "Copying file index.html to /var/www/doap.com/"
          scp -o StrictHostKeyChecking=no index.html dmenache@deb1.doap.com:/var/www/doap.com/

          echo "Copying file simple.php to /var/www/doap.com/"
          scp -o StrictHostKeyChecking=no simple.php dmenache@deb1.doap.com:/var/www/doap.com/

          echo "Copying images directory to /var/www/doap.com/images/"
          #scp -r -o StrictHostKeyChecking=no images/ dmenache@deb1.doap.com:/var/www/doap.com/images/

          echo "Copying inc directory to /var/www/doap.com/inc/"
          #scp -r -o StrictHostKeyChecking=no inc/ dmenache@deb1.doap.com:/var/www/doap.com/inc/

          echo "Sending Email Notification"
          echo '<html>
          <head>
            <title>Doap.com Repo Deployed</title>
          </head>
          <body>
            <p><strong>Files Deployed:</strong></p>
            <ul>
              <li>index.html</li>
              <li>simple.php</li>
              <li>images/</li>
              <li>inc/</li>
            </ul>
            <p>Deployed to repo and fleet: <a href="https://github.com/menached/doap.com/actions">https://github.com/menached/doap.com/actions</a></p>
          </body>
          </html>' | mail -s "Code Deployed" -a "Content-Type: text/html" info@doap.com

