name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH Agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Install Mailutils
      - name: Install Mailutils
        run: |
          sudo apt update
          sudo apt install -y mailutils

      # Step 4: Get Changed Files
      - name: Get Changed Files
        id: changes
        run: |
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "First commit, taking all files."
            git ls-files > changed_files.txt
          else
            echo "Getting changed files since last commit."
            git diff --name-only HEAD^ > changed_files.txt
          fi
          echo "Changed files:"
          cat changed_files.txt

      # Step 5: Deploy Changed Files
      - name: Deploy Changed Files
        run: |
          echo "Copying changed files to server and syncing with S3 and CloudFront..."
          while read -r file; do
            echo "Processing $file"
            # Copy to server
            scp -o StrictHostKeyChecking=no "$file" dmenache@deb1.doap.com:/var/www/doap.com/"$file"

            # Sync with S3
            aws s3 cp "$file" s3://www.doap.com/"$file"

            # Invalidate CloudFront
            aws cloudfront create-invalidation --distribution-id E3MM919ZQPQJTL --paths "/$file"
          done < changed_files.txt

      # Step 6: Send Email Notification
      - name: Send Email Notification
        run: |
          echo "Sending Email Notification"
          EMAIL_BODY="<html>
          <head>
            <title>Doap.com Repo Deployed</title>
          </head>
          <body>
            <p><strong>Files Deployed:</strong></p>
            <ul>"
          while read -r file; do
            EMAIL_BODY+="<li>$file</li>"
          done < changed_files.txt
          EMAIL_BODY+="</ul>
          <p>Deployed to repo and fleet: <a href='https://github.com/menached/doap.com/actions'>https://github.com/menached/doap.com/actions</a></p>
          </body>
          </html>"
          echo "$EMAIL_BODY" | mail -s "Doap.com repo Deployed" -a "Content-Type: text/html" info@doap.com

