name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH Agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Copy Files to Apache vhost
      - name: Copy Files to Apache vhost
        run: |
          echo "Copying file index.html to /var/www/doap.com/"
          scp -o StrictHostKeyChecking=no index.html dmenache@deb1.doap.com:/var/www/doap.com/
          echo "Copying file simple.php to /var/www/doap.com/"
          scp -o StrictHostKeyChecking=no simple.php dmenache@deb1.doap.com:/var/www/doap.com/
          echo "Email notification"
          #echo "index.html and simple.php deployed to repo and fleet https://github.com/menached/doap.com/actions" | mail -s "code deployed" info@doap.com 
          echo '<html>
          <head>
            <title>Code Deployed</title>
          </head>
          <body>
            <p><strong>Files Deployed:</strong></p>
            <ul>
              <li>index.html</li>
              <li>simple.php</li>
            </ul>
            <p>Deployed to repo and fleet: <a href="https://github.com/menached/doap.com/actions">https://github.com/menached/doap.com/actions</a></p>
          </body>
          </html>' | mail -s "Code Deployed" -a "Content-Type: text/html" info@doap.com 


