name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Mailutils
        run: |
          sudo apt update
          sudo apt install -y mailutils

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "${{ secrets.AWS_REGION }}"

      - name: Get Changed Files
        id: changes
        run: |
          git fetch origin main
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            git ls-files > changed_files.txt
          else
            git diff --name-only origin/main > changed_files.txt
          fi
          echo "Changed files:"
          cat changed_files.txt

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no dmenache@deb1.doap.com "echo 'SSH Connection Successful'"

      - name: Debug Changed Files
        run: |
          echo "Contents of changed_files.txt:"
          cat changed_files.txt

      - name: Deploy Changed Files
        run: |
          while IFS= read -r file || [ -n "$file" ]; do
            echo "Processing $file"

            if [ ! -f "$file" ]; then
              echo "File $file does not exist! Skipping..."
              continue
            fi

            DEST_DIR=$(dirname "/var/www/doap.com/$file")
            ssh -o StrictHostKeyChecking=no dmenache@deb1.doap.com "mkdir -p $DEST_DIR"
            scp -v -o StrictHostKeyChecking=no "$file" dmenache@deb1.doap.com:/var/www/doap.com/"$file"
          done < changed_files.txt
